### ISSUE TITLE
[Java] total number of tests fluctuates

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-raptor#436]
Test discovery is acting unexpectedly. Total number of tests fluctuates from one run to another.

**Comment by zengin** [comment]
This is not a test discovery bug. There is a memory management bug in the way objects are disposed in Java compilation.

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at Interop.Kernel32.SetEvent(SafeWaitHandle handle)
   at System.Threading.EventWaitHandle.Set()
   at MsGraphSDKSnippetsCompiler.MicrosoftGraphJavaCompiler.<>c__DisplayClass17_0.<CompileSnippet>b__0(Object sender, DataReceivedEventArgs e) in /agent/_work/1/s/msgraph-sdk-raptor/msgraph-sdk-raptor-compiler-lib/MicrosoftGraphJavaCompiler.cs:line 129
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

```

cc: @georgend @rkodev @nikithauc, the underlying reason could be the same for TypeScript compilation failures as the process stdout redirection code is taken from Java.
